services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: box-tournament-backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "5801:5000"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: box-tournament-frontend
    restart: always
    ports:
      - "5800:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
